### PR TITLE
openssl 1.1.x and 1.0.x md compatibility, add --not-secure option

### PR DESCRIPTION
**Pull request by schenot**

### CODE REVIEW

**Comment by camathieu** [comment]
Great thanks :)

Would be great to add a test case for the new option in client/test.sh

The travis build tests are failing but it's not your fault I believe that the go lint tool has been updated with new cases recently :
- file ./metadataBackend/metadataBackend.go : FAIL
- file ./dataBackend/dataBackend.go : FAIL

**Comment by camathieu** [comment]
This will fix the build https://github.com/root-gg/plik/pull/250
I'll tell you when it's prodded so you can rebase.

**Comment by camathieu** [comment]
done

**Comment by schenot** [comment]
Code is rebased and test for the --not-secure option is added to the client/test.sh script, tell me if it's sound good to you.

**Comment by camathieu** [comment]
Awesome :)

**Pull request merged**
