### PR TITLE
[Ux] Correct 'directory' link

### PR DESCRIPTION
**Pull request by Renayzz**

### CODE REVIEW

**Comment by camathieu** [comment]
We went with removing the hashbang prefix in 1.2.2 because it has been deprecated by Google.

Please see :
https://github.com/root-gg/plik/commit/7981136e3f1f5b98ba59f9b40444677136b7ebd6#diff-7b57cbaf6fd3ee57b6e4252bcdcc3448R325

Especially

https://github.com/root-gg/plik/blob/7981136e3f1f5b98ba59f9b40444677136b7ebd6/server/public/js/app.js#L325

**Comment by Renayzz** [comment]
I found my mistake : docker image isn't up to date

**Comment by camathieu** [comment]
You are right totally forgot to update it. I'll do it asap.

**Comment by camathieu** [comment]
Done, sorry for the delay I was unable to build the image because of an issue with the version of nodejs/npm were using on that server. 

I'll take a look at building the docker images automatically when we merge to master / create new tags.

**Pull request closed without merging**
