### PR TITLE
Fix #85: Config url with trailing / fail

### LINKED ISSUE #85: Config url with trailing / fail
When adding an url like `https://plik.root.gg/`  
the trailing `/` make it fail (redirection)

Validating inputed url with https://golang.org/pkg/net/url/#Parse would also be nice :)

### PR DESCRIPTION
**Pull request by cyrbil**
Remove slash in given domain as it breaks later usage of it.
Parse url with standard lib and refactor scheme check.

### CODE REVIEW

**Comment by bodji** [comment]
Seems good to me !

**Comment by cyrbil** [comment]
Hum ... strange the build passes ... but I forgot `import "net/url"` :sweat_smile:

**Comment by bodji** [comment]
No it's broken.

# github.com/root-gg/plik/client/config
../../../go/src/github.com/root-gg/plik/client/config/config.go:164: undefined: url

Can you fix, and make a second pull request please ?

**Comment by cyrbil** [comment]
https://github.com/root-gg/plik/pull/87

**Pull request merged**
