### PR TITLE
Fix early abort on files deletion loop

### LINKED ISSUE #352: Unable to delete files
I noticed that on our instance of Plik files weren't being removed after they expired so I took a look at the logs and found the following:

[01/13/2021 15:47:32][WARNING ] unable to delete file zLWxo9KAgtTktxiJ/pbPFN5vCHKI8eI4p : no such file or directory
[01/13/2021 15:47:32][WARNING ] no such file or directory
Can't remove upload zLWxo9KAgtTktxiJ because 1 files are still not deleted
Can't remove upload AfLAYpe7bIukTxhb because 1 files are still not deleted
Can't remove upload 1gD7wZTNxrk8CYwt because 1 files are still not deleted

This continues for a while. There's now a backlog of undeleted files for about a month even though the max ttl is set to a week.

What can cause this behavior and why does it also affect the future uploaded files?

### LINKED ISSUE #353: not deleting files on filesystem
Hey there,

does that happen just for me or does someone else have the same issue? uploaded files won't delete from the filesystem.

to reproduce: add an upload, set the config to delete after first download or only there for some days or delete it manually after uploaded, the file will no longer be access able through the user interface, but when you look into the files folder of plik (/home/plik/server/files) there is still the content.

can someone reproduce that behaviour or is my config just faulty?

### PR DESCRIPTION
**Pull request by speed47**
Closes #352
Closes #353

### CODE REVIEW

**Comment by speed47** [comment]
Currently being tested to enssure it does fix the problem as it should.

**Comment by camathieu** [comment]
Let me know how it goes, I'll make a new release if you like

**Comment by speed47** [comment]
It works, all the files older than 30 days finally vanished from the FS :)

**Comment by camathieu** [comment]
no more travis builds :'(

**Comment by speed47** [comment]
> no more travis builds :'(

Aww, yep :/ Hopefully migrating to GitHub Actions is not too painful starting from the workflow you had with travis

**Comment by camathieu** [comment]
I ran tests locally and it seems fine, we might want add a test case though.
I'll try to take a look at GA tomorrow or Friday and to cut a 1.3.2 release with the last few patches.

**Comment by camathieu** [comment]
Thanks for the patch :)

**Pull request merged**
