### PR TITLE
Add Download domain alias.

### PR DESCRIPTION
**Pull request by d-w-x**
We can use it for CDN, internal download etc.

### CODE REVIEW

**Comment by camathieu** [comment]
Looks good to me but could you please add tests to the PR ?

**Comment by camathieu** [comment]
I'm thinking renaming the config parameter DownloadDomains might be a simpler approach.

**Comment by camathieu** [comment]
I reworked your code a bit and added tests as I want to release 1.3.6 today or maybe tomorrow.
I created a new PR with your commit and a rework commit on top : https://github.com/root-gg/plik/pull/443
I'm going to close this one.
Thank you very much for your contribution <3.

**Comment by d-w-x** [comment]
Thanks for your change. I was a little busy last few days, and sorry for the late replay.
Actually, I'm not familiar with go, my PR is just the minimal changes which I think could work and passed all existed tests.
Thanks for the excellent software.

**Pull request closed without merging**
